"""empty message

Revision ID: 9d324dabade9
Revises: ec6e3d7e265a
Create Date: 2019-03-15 15:01:29.311861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d324dabade9'
down_revision = 'ec6e3d7e265a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=120), nullable=False))
    op.drop_constraint(u'users_password1_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['password'])
    op.drop_column('users', 'password1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password1', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_password1_key', 'users', ['password1'])
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
